#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# ./0-transfer_file file_name ip_address username ~/.ssh/id_key.pub
# example ./0-transfer_file 54.146.74.212 ubuntu ~/.ssh/id_key.pub

if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 3 ]
then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
